# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
POST http://127.0.0.1:8000/threads/start
Accept: application/json
Content-Type: application/json

{
  "sender_id": 1,
  "receivers": [2, 3],
  "message": "Test Subject"
}

###
GET http://127.0.0.1:8000/threads
Accept: application/json

###

GET http://127.0.0.1:8000/threads/1
Accept: application/json

###
POST http://127.0.0.1:8000/threads/reply/1
Accept: application/json
Content-Type: application/json

{
  "sender_id": 2,
  "visible_to_strangers": true,
  "message": "Hello to you once more!"
}

###
POST http://127.0.0.1:8000/users/create
Accept: application/json
Content-Type: application/json

{
  "username": "Jasmijn",
  "password" : "321cba"
}

###

GET http://127.0.0.1:8000/users/1
Accept: application/json